apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    key: value
    app: myapp
    type: front-end
spec: 
  conatiners:
    - name: nginx-container
      image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoreDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size                                           
            operator: In
            values:
            - Large
            - Medium

          #  or
          - key: size
            operator: NotIn
            values:
            - Small

          #
          - key: size
            operator: Exists
