apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["Sleep2.0"] #overrides ENTRYPOINT instruction in dockerfile
    args: ["10"] #overrrides CMD instruction in dockerfile
  
    env:
      - name: APP_COLOUR      #plain key
        value: pink

    env:
      - name: APP_COLOUR
        valueFrom:             #configmap defining         
          configMapKeyRef:
    
    env:
      - name: APP_COLOUR
        valueFrom:              # secret deefining
          secretKeyRef:


Dockerfile

FROM ubuntu
ENTRPOINT ["sleep"]
CMD ["5"]

docker run -e APP_COLOUR=pink simplewebcolour
