apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    key: value
    app: myapp
    type: front-end
spec: 
  conatiners:
    - name: ubuntu-image
      image: ubuntu
      command: ["sleep","3600"]
      securityContext:
        runAsUser: 1000
        capabilities:
          add: ["MAC-ADMIN"]
#conatiner level security contexts overides the pod level security
# capabilities are only supported at pod level
#kubernetes level security
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    key: value
    app: myapp
    type: front-end
spec:
  securityContext:
      runAsUser: 1000
  conatiners:
    - name: ubuntu-image
      image: ubuntu
      command: ["sleep","3600"]
