apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    key: value
    app: myapp
    type: front-end
spec: 
  conatiners:
    - name: nginx-container
      image: nginx
  tolerations:
    - key: "app"
      operator: "Equal"
      value: "blue"
      effect: "NoSchedueles"
